title: Mark Everard - Founder @firstthreethings and Optimizely MVP
description: Blog home of Mark Everard - Founder @firstthreethings and Optimizely MVP. The site is collection of my thoughts and posts from my 20 year martech career. I aspire to write more.
permalink: ':year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.markeverard.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mark Everard # add your name
author-img: mark-everard.jpg # add your photo
about-author: Founder <a href="https://www.ftt.ai">@first3things</a>, CTO, Architect, <a href="https://world.optimizely.com/community/omvp/members/">Optimizely MVP</a>. PhD physicist turned hands on tech leader. Show me the code.

social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: markeverard # add your Github handle
social-linkedin: everard
social-email: # add your Email address

# Disqus
discus-identifier: markeverard # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
